### ISSUE TITLE
[Desafio calculadora usando arrow function

### ISSUE THREAD

**Issue by DawiMessias** [jsraiz/desafios#2]
Fala senhores, estou fazendo o 1 desafio iniciante da calculadora, tentei fazer com retorno direto por hora somente no backend, vou anexar imagens do código, por algum motivo não sei se meus retornos estão certos, tentei retornar diretamente o "abaixo do peso" valor do imc da pessoa, mas não consigo.
![image](https://user-images.githubusercontent.com/52683766/150011534-bbf0f7e0-4ccb-4fbd-a26a-1d6dc0588775.png)
![image](https://user-images.githubusercontent.com/52683766/150011571-ab2a8179-b16b-4b2c-bee2-b6aa3571b905.png)

**Comment by ayrtonteshima** [comment]
Fala Dawi! Você ali definou as functions (arrow functions) mas em nenhum momento você executou elas, por isso não tem resultado.
Você teria, por exemplo, fazer o seguinte:
```js
console.log(abaixoPeso(imc))
```
Assim ele vai retornar o 'abaixo do peso' ou o próprio imc.

De alguma forma você tem que invocar essas functions que definiu..

**Comment by DawiMessias** [comment]
Opa então a lógica da para dizer que está certa né, alguma coisa que você melhoraria ?

**Comment by ayrtonteshima** [comment]
A sua lógica parece muito uma que ensino no módulo de qualidade de código utilizando o método `find`. CAso queira dar uma olhada lá, acho que vai ficar muito boa a solução.

Se você não utilizar uma solução semelhante ao find, as functions que você criou não vai adiantar muito pois você vai ter que testar uma por uma com uma condicional (usando o find ele procura pra você "automaticamente")

Mas avance, trabalhe a lógica e mande novamente que é o melhor caminho ! :)

**Comment by DawiMessias** [comment]
Opa vlw seu Ayrton :), mt obg
